version: '3'

services:
  app:
    image: node:16.6.1-alpine
    volumes:
      - ./:/myapp
    working_dir: /myapp
    command: ["npm", "run", "start"]
    ports:
      - '3000:3000'
    tty: true
    stdin_open: true